services:
  loci-db:
    container_name: loci-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: locidb
    volumes:
      # - ./loci-db:/data/postgres
      - ./postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
      # - ./postgres-entrypoint.sh:/postgres-entrypoint.sh
    # entrypoint: ["postgres-entrypoint.sh"]

    ports:
      - 5432:5432
    networks:
      - loci-net

  loci-pgadmin:
    container_name: loci-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - loci-net




  loci-keycloak:
    container_name: loci-keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL_HOST: loci-db
        KC_DB_URL_DATABASE: locidb
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: admin
    networks:
      - loci-net
    depends_on:
      - loci-db
    volumes:
      # - ./apps/keycloak/import:/opt/keycloak/data/import
      # - loci-keycloak:/opt/keycloak/data
      - ./keycloak-data:/opt/keycloak/data/
      # User export as the data import
      # - ./keycloak-data/export/:/opt/keycloak/data/import

    command:
      start-dev --import-realm

  loci-minio:
    image: minio/minio
    container_name: loci-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=loci-bucket-01
    networks:
      - loci-net
    volumes:
      - loci-minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  loci-minio-mc:
    image: minio/mc:latest
    container_name: minio_client
    depends_on:
      - loci-minio
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-loci-bucket-01}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://loci-minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin};
      /usr/bin/mc mb local/${BUCKET_NAME:-loci-bucket-01};
      /usr/bin/mc anonymous set public local/${BUCKET_NAME:-loci-bucket-01};
      tail -f /dev/null;
      exit 0;
      "
    networks:
      - loci-net
networks:
  loci-net:
    driver: bridge
volumes:
  loci-db:
    driver: local
  loci-keycloak:
    driver: local
  loci-minio:
    driver: local
