info:
  name: currentUserProfileSettings
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}/users/me/settings"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: OK
    request:
      url: "{{baseUrl}}/users/me/settings"
      method: GET
    response:
      statusText: OK
      headers:
        - name: Content-Type
          value: "*/*"
      body:
        type: text
        data: |-
          {
            "lastSeenSetting": "",
            "friendRequests": "",
            "profileVisibility": false
          }
