services:
  loci-db:
    container_name: loci-db
    image: postgres:18.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: locidb
    volumes:
      - loci-db:/data/postgres
      ## Init script sql
      # - ./backups:/backups
      # - ./backups/backup.sql:/docker-entrypoint-initdb.d/init.sql
      ## Entry point to access via script
      # - ./scripts/postgres-entrypoint.sh:/postgres-entrypoint.sh
      # - ./scripts/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/initdb.sh

    # entrypoint: ["postgres-entrypoint.sh"]

    ports:
      - 5432:5432
    networks:
      - loci-net

  loci-pgadmin:
    container_name: loci-pgadmin
    image: dpage/pgadmin4:9.11
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - loci-net

  loci-keycloak:
    container_name: loci-keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: loci-db
      KC_DB_URL_DATABASE: locidb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    networks:
      - loci-net
    depends_on:
      - loci-db
    volumes:
      # - ./apps/keycloak/import:/opt/keycloak/data/import
      # - loci-keycloak:/opt/keycloak/data
      - ./keycloak-data:/opt/keycloak/data/
      # User export as the data import
      # - ./keycloak-data/export/:/opt/keycloak/data/import

    command: start-dev --import-realm

  loci-rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: "loci-mq"
    ports:
      - 5672:5672 # Message broker
      - 15672:15672 # UI manager
      - 61613:61613 # Relay
    volumes:
      - loci-rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins # Use to enable stomp plugin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - loci-net

  loci-prometheus:
    image: prom/prometheus:v2.45.0
    container_name: loci-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10d" # 10-day retention
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle" # Allows hot-reload via API
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    # network_mode: host
    ports:
      - "9092:9090"
    networks:
      - loci-net
    extra_hosts:
      # Access via dns
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # Visualization

  loci-grafana:
    image: grafana/grafana:10.0.0
    container_name: loci-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - DS_PROMETHEUS=Prometheus
      # Optional: Disable auth for local dev

      # NOTE: remove for production
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning/dashboards/:/etc/grafana/dashboards:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - loci-net
    depends_on:
      - loci-prometheus
    restart: unless-stopped

  loci-minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: loci-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=loci-bucket-01
    networks:
      - loci-net
    volumes:
      - loci-minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  loci-minio-mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: minio_client
    depends_on:
      - loci-minio
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-loci-bucket-01}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://loci-minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin};
      /usr/bin/mc mb local/${BUCKET_NAME:-loci-bucket-01};
      /usr/bin/mc anonymous set public local/${BUCKET_NAME:-loci-bucket-01};
      tail -f /dev/null;
      exit 0;
      "
    networks:
      - loci-net

networks:
  loci-net:
    driver: bridge
volumes:
  loci-db:
    driver: local
  loci-keycloak:
    driver: local
  loci-minio:
    driver: local
  loci-rabbitmq:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
