global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8080"] # Must match service name in docker-compose
    # Optional: Add labels to identify instance
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "your-app-local"
